version: 2.1
orbs:
  node: circleci/node@1

jobs:
  test:
    docker:
      - image: cypress/base:12.1.0
    steps:
      - checkout
      - node/with-cache:
          dir: ~/.npm
          steps:
            - run: npm ci
            - run: npm t

workflows:
  version: 2
  build:
    jobs:
      - test
