version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  test:
    docker:
      - image: cypress/base:12.6.0
    steps:
      - checkout
      - node/with-cache:
          dir: ~/.npm
          steps:
            - run: npm ci
            - run:
                command: npm ci
                working_directory: test-debug-v2
            - run: npm t
            - run:
                command: npm t
                working_directory: test-debug-v2
            - run: npm run stop-only
            - run: npm run semantic-release

workflows:
  version: 2
  build:
    jobs:
      - test
